ageWeight(gk,X).
heightWeight(gk,X).
ratingWeight(gk,X).
accuratePassesPercentageWeight(gk,X).
redCardsWeight(gk,X).
penaltyConcededWeight(gk,X).
accurateLongBallsPercentageWeight(gk,X).
ownGoalsWeight(gk,X).
errorLeadToGoalWeight(gk,X).
savesWeight(gk,X).
cleanSheetWeight(gk,X).
penaltyPercentageWeight(gk,X).
insideTheBoxWeight(gk,X).
outsiteTheBoxWeight(gk,X).
goalsConcededInsideTheBoxWeight(gk,X).
goalsConcededOutsideTheBoxWeight(gk,X).
goalsConcededWeight(gk,X).
mpWeight(gk,X).
ageWeight(dc,X).
heightWeight(dc,X).
ratingWeight(dc,X).
goalsWeight(dc,X).
accuratePassesPercentageWeight(dc,X).
interceptionsWeight(dc,X).
yellowCardsWeight(dc,X).
groundDuelsWonPercentageWeight(dc,X).
aerialDuelsWonPercentageWeight(dc,X).
redCardsWeight(dc,X).
penaltyConcededWeight(dc,X).
accurateLongBallsPercentageWeight(dc,X).
ownHalfPassesPercentageWeight(dc,X).
clearancesWeight(dc,X).
ownGoalsWeight(dc,X).
errorLeadToGoalWeight(dc,X).
errorLeadToShotWeight(dc,X).
blockedShotsWeight(dc,X).
dispossessedWeight(dc,X).
possessionLostWeight(dc,X).
foulsWeight(dc,X).
dribbledPastWeight(dc,X).
tacklesWonPercentageWeight(dc,X).
cleanSheetWeight(dc,X).
goalsConcededWeight(dc,X).
mpWeight(dc,X).
ageWeight(fb,X).
heightWeight(fb,X).
ratingWeight(fb,X).
goalsWeight(fb,X).
bigChancesCreatedWeight(fb,X).
accuratePassesPercentageWeight(fb,X).
accurateFinalThirdPassesWeight(fb,X).
keyPassesWeight(fb,X).
successfulDribblesPercentageWeight(fb,X).
interceptionsWeight(fb,X).
yellowCardsWeight(fb,X).
redCardsWeight(fb,X).
penaltyConcededWeight(fb,X).
accurateCrossesPercentageWeight(fb,X).
groundDuelsWonPercentageWeight(fb,X).
aerialDuelsWonPercentageWeight(fb,X).
penaltyWonWeight(fb,X).
accurateLongBallsPercentageWeight(fb,X).
clearancesWeight(fb,X).
errorLeadToGoalWeight(fb,X).
dispossessedWeight(fb,X).
possessionLostWeight(fb,X).
possessionWonAttThirdWeight(fb,X).
wasFouledWeight(fb,X).
foulsWeight(fb,X).
ownGoalsWeight(fb,X).
dribbledPastWeight(fb,X).
tacklesWonPercentageWeight(fb,X).
ownHalfPassesPercentageWeight(fb,X).
oppositionHalfPassesPercentageWeight(fb,X).
assistsWeight(fb,X).
errorLeadToShotWeight(fb,X).
blockedShotsWeight(fb,X).
goalsConcededWeight(fb,X).
cleanSheetWeight(fb,X).
mpWeight(fb,X).
ageWeight(dm,X).
heightWeight(dm,X).
ratingWeight(dm,X).
goalsWeight(dm,X).
bigChancesCreatedWeight(dm,X).
accuratePassesPercentageWeight(dm,X).
keyPassesWeight(dm,X).
successfulDribblesPercentageWeight(dm,X).
interceptionsWeight(dm,X).
yellowCardsWeight(dm,X).
redCardsWeight(dm,X).
penaltyConcededWeight(dm,X).
groundDuelsWonPercentageWeight(dm,X).
aerialDuelsWonPercentageWeight(dm,X).
accurateLongBallsPercentageWeight(dm,X).
errorLeadToGoalWeight(dm,X).
dispossessedWeight(dm,X).
possessionLostWeight(dm,X).
tacklesWonPercentageWeight(dm,X).
assistsWeight(dm,X).
dribbledPastWeight(dm,X).
ownHalfPassesPercentageWeight(dm,X).
oppositionHalfPassesPercentageWeight(dm,X).
foulsWeight(dm,X).
ownGoalsWeight(dm,X).
errorLeadToShotWeight(dm,X).
blockedShotsWeight(dm,X).
passToAssistWeight(dm,X).
goalsConcededWeight(dm,X).
cleanSheetWeight(dm,X).
mpWeight(dm,X).
ageWeight(mc,X).
heightWeight(mc,X).
ratingWeight(mc,X).
goalsWeight(mc,X).
bigChancesCreatedWeight(mc,X).
accuratePassesPercentageWeight(mc,X).
keyPassesWeight(mc,X).
successfulDribblesPercentageWeight(mc,X).
interceptionsWeight(mc,X).
yellowCardsWeight(mc,X).
redCardsWeight(mc,X).
accurateCrossesPercentageWeight(mc,X).
penaltyConcededWeight(mc,X).
groundDuelsWonPercentageWeight(mc,X).
aerialDuelsWonPercentageWeight(mc,X).
accurateLongBallsPercentageWeight(mc,X).
errorLeadToGoalWeight(mc,X).
dispossessedWeight(mc,X).
possessionLostWeight(mc,X).
tacklesWonPercentageWeight(mc,X).
assistsWeight(mc,X).
dribbledPastWeight(mc,X).
ownHalfPassesPercentageWeight(mc,X).
oppositionHalfPassesPercentageWeight(mc,X).
accurateFinalThirdPassesWeight(mc,X).
foulsWeight(mc,X).
ownGoalsWeight(mc,X).
errorLeadToShotWeight(mc,X).
passToAssistWeight(mc,X).
goalsConcededWeight(mc,X).
possessionWonAttThirdWeight(mc,X).
mpWeight(mc,X).
ageWeight(am,X).
heightWeight(am,X).
ratingWeight(am,X).
goalsWeight(am,X).
bigChancesMissedWeight(am,X).
bigChancesCreatedWeight(am,X).
keyPassesWeight(am,X).
successfulDribblesPercentageWeight(am,X).
interceptionsWeight(am,X).
yellowCardsWeight(am,X).
redCardsWeight(am,X).
accuratePassesPercentageWeight(am,X).
accurateCrossesPercentageWeight(am,X).
groundDuelsWonPercentageWeight(am,X).
aerialDuelsWonPercentageWeight(am,X).
accurateLongBallsPercentageWeight(am,X).
dispossessedWeight(am,X).
possessionLostWeight(am,X).
assistsWeight(am,X).
penaltyWonWeight(am,X).
oppositionHalfPassesPercentageWeight(am,X).
accurateFinalThirdPassesWeight(am,X).
passToAssistWeight(am,X).
possessionWonAttThirdWeight(am,X).
wasFouledWeight(am,X).
goalConversionPercentageWeight(am,X).
scoringFrequencyWeight(am,X).
mpWeight(am,X).
ageWeight(st,X).
heightWeight(st,X).
ratingWeight(st,X).
goalsWeight(st,X).
bigChancesMissedWeight(st,X).
bigChancesCreatedWeight(st,X).
keyPassesWeight(st,X).
successfulDribblesPercentageWeight(st,X).
yellowCardsWeight(st,X).
redCardsWeight(st,X).
groundDuelsWonPercentageWeight(st,X).
aerialDuelsWonPercentageWeight(st,X).
dispossessedWeight(st,X).
possessionLostWeight(st,X).
assistsWeight(st,X).
oppositionHalfPassesPercentageWeight(st,X).
accurateFinalThirdPassesWeight(st,X).
wasFouledWeight(st,X).
goalConversionPercentageWeight(st,X).
scoringFrequencyWeight(st,X).
mpWeight(st,X).
ageWeight(w,X).
heightWeight(w,X).
ratingWeight(w,X).
goalsWeight(w,X).
bigChancesMissedWeight(w,X).
bigChancesCreatedWeight(w,X).
accuratePassesPercentageWeight(w,X).
keyPassesWeight(w,X).
penaltyWonWeight(w,X).
successfulDribblesWeight(w,X).
yellowCardsWeight(w,X).
redCardsWeight(w,X).
accurateCrossesPercentageWeight(w,X).
groundDuelsWonPercentageWeight(w,X).
aerialDuelsWonPercentageWeight(w,X).
dispossessedWeight(w,X).
possessionLostWeight(w,X).
assistsWeight(w,X).
oppositionHalfPassesPercentageWeight(w,X).
accurateFinalThirdPassesWeight(w,X).
passToAssistWeight(w,X).
wasFouledWeight(w,X).
cleanSheetWeight(w,X).
goalConversionPercentageWeight(w,X).
mpWeight(w,X).
